# Docs/refresh_docs.py
# Purpose: Always rebuild Docs/USER_GUIDE.md and Docs/DEV_GUIDE.md from scratch,
# regenerate Docs/SCRIPTS_INDEX.md, inject hybrid flow, scenario tables, and
# auto-fix unclosed ``` fences. No PDF export. Simple, deterministic logs.

import json, re, sys, time
from pathlib import Path
from typing import List, Tuple

# ---------------- Config ------------------------------------------------------

REPO_ROOT              = Path(".").resolve()
DOCS_DIR               = REPO_ROOT / "Docs"
USER_GUIDE_PATH        = DOCS_DIR / "USER_GUIDE.md"
DEV_GUIDE_PATH         = DOCS_DIR / "DEV_GUIDE.md"
SCRIPTS_INDEX_PATH     = DOCS_DIR / "SCRIPTS_INDEX.md"
SCRIPT_EXTENSIONS      = {".py", ".ps1", ".cmd", ".bat"}
IGNORE_SUBSTRINGS      = {".git", "venv", "__pycache__"}
REQUIRED_SCRIPTS       = [
    "scripts/run_day_simple.py",
    "scripts/summarize_results.py",
    "scripts/topgappers.py",
    "scripts/fetch_minutes_polygon.py",
    "scripts/run_all_scenarios.ps1",
]

# ---------------- Helpers -----------------------------------------------------

def log(msg: str): print(msg, flush=True)
def err(msg: str): print(msg, file=sys.stderr, flush=True)

def _finalize_markdown(md_text: str) -> str:
    count = md_text.count("```")
    if count % 2 == 1:
        if not md_text.endswith("\n"):
            md_text += "\n"
        md_text += "```\n"
    if not md_text.endswith("\n"):
        md_text += "\n"
    return md_text

def read_text(p: Path) -> str:
    try:
        return p.read_text(encoding="utf-8")
    except Exception:
        return ""

def write_text(p: Path, content: str):
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(_finalize_markdown(content), encoding="utf-8")
    log(f"[Docs] Wrote {p}")

def is_ignored(p: Path) -> bool:
    s = p.as_posix().lower()
    return any(tok in s for tok in IGNORE_SUBSTRINGS)

# ---------------- Scripts Index ----------------------------------------------

def generate_scripts_index() -> Tuple[str, List[str]]:
    files: List[Path] = []
    for p in REPO_ROOT.rglob("*"):
        if p.is_file() and p.suffix.lower() in SCRIPT_EXTENSIONS and not is_ignored(p):
            files.append(p)

    lines = [
        "# Script Index",
        "",
        "(auto-generated by refresh_docs.py; do not edit by hand)",
        "",
    ]
    for p in sorted(files, key=lambda x: x.as_posix().lower()):
        rel = p.relative_to(REPO_ROOT).as_posix()
        try:
            with open(p, "r", errors="ignore", encoding="utf-8") as fh:
                first = (fh.readline() or "").strip()
        except Exception:
            first = ""
        mtime = time.strftime("%Y-%m-%d", time.localtime(p.stat().st_mtime))
        lines.append(f"- `{rel}` — {mtime} — {first[:160]}")

    md = "\n".join(lines)
    write_text(SCRIPTS_INDEX_PATH, md)

    missing: List[str] = [r for r in REQUIRED_SCRIPTS if not (REPO_ROOT / r).exists()]
    return md, missing

# ---------------- Scenarios Table from config/scenarios.json ------------------

SCENARIO_TABLE_HEADER = (
    "| Scenario | tp_pct | sl_pct | ema_confirm | vwap_confirm | macd_confirm | dip_reclaim | min_dip_pct | min_reclaim_pct | reclaim_ref | ema_period | gate_minutes | rise_bars | min_pm_vol |\n"
    "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"
)

def _row(params: dict, name: str) -> str:
    def g(k, d=""): return params.get(k, d)
    return "| " + " | ".join([
        name,
        str(g("tp_pct")), str(g("sl_pct")),
        str(g("ema_confirm")), str(g("vwap_confirm")), str(g("macd_confirm")),
        str(g("dip_reclaim")), str(g("min_dip_pct")), str(g("min_reclaim_pct")),
        str(g("reclaim_ref")), str(g("ema_period")), str(g("gate_minutes")),
        str(g("rise_bars")), str(g("min_pm_vol")),
    ]) + " |"

def build_scenario_tables() -> Tuple[str, str]:
    cfg = REPO_ROOT / "config" / "scenarios.json"
    try:
        data = json.loads(read_text(cfg)) if cfg.exists() else {}
    except Exception:
        data = {}
    order = [k for k in ["A","B","C","D","E"] if k in data]
    if not order:
        return "", ""

    rows = [SCENARIO_TABLE_HEADER] + [_row(data[k]["params"], k) for k in order]
    summary_table = "\n".join(rows) + "\n\n"

    json_header = "| Scenario | Source | Params (JSON) |\n|---|---|---|"
    json_rows  = [f'| {k} | config\\scenarios.json | {json.dumps(data[k]["params"], separators=(",",":"))} |' for k in order]
    json_table = json_header + "\n" + "\n".join(json_rows) + "\n\n"

    return summary_table, json_table

# ---------------- Content Builders -------------------------------------------

HYBRID_SINGLE = (
    "## Catalyst Hybrid — Single Day (auto)\n\n"
    "```powershell\n"
    "python scripts/run_catalyst_flow.py --date 2025-08-05 --scenario B --news-first --news-min-score 1 --top 12 --enforce-band\n"
    "```\n\n"
    "**What this does**\n"
    "- Uses **news-first** selection; fills with RAW gappers up to **Top-12** within the enforce-band (price/gap).\n"
    "- Wrapper passes the **full RAW file path** to compose; compose builds **news + RAW fillers**.\n"
    "- Runs Scenario **B** on the hybrid universe.\n"
)

HYBRID_RANGE = (
    "## Catalyst Hybrid — Date Range (auto)\n\n"
    "```powershell\n"
    "python scripts/run_catalyst_flow.py --start 2025-08-05 --end 2025-08-07 --scenario B --news-first --news-min-score 1 --top 12 --enforce-band\n"
    "```\n\n"
    "**Notes**\n"
    "- Consider enabling an **opening RVOL gate** in config/scenarios.json (e.g., ≥1.5× first 10–15m vs prior day).\n"
    "- Optional headline polarity filter in `enrich_universe_catalyst.py` (e.g., `--deny-negative` with `data/catalyst/neg_terms.txt`).\n"
)

HYBRID_NOTES = (
    "### Catalyst Hybrid Notes (auto)\n\n"
    "- Compose expects **full RAW path** for `--raw`, e.g. `data/raw/universe_topgappers_<DATE>.txt`.\n"
    "- Using a prefix may produce `rawTop=0` (news-only).\n"
)

RUN_DAY_SUCCESS = (
    "## Run-Day Success Sequence (auto)\n\n"
    "### Overview\n"
    "This section documents the *successful* sequence after running:\n"
    "`python scripts/run_day_simple.py --date YYYY-MM-DD --scenario B`\n\n"
    "1. **Top gappers fetched** (Polygon or your source)\n"
    "2. **Universe file written** (e.g., `data/samples/universe_sample.txt`)\n"
    "3. **Minute data fetched** into `data/...`\n"
    "4. **Backtest runs** for chosen scenario; results to `out/<YYYYMMDD>/<Scenario>/results_YYYY-MM-DD.csv`\n"
    "5. **Summarize** via `python scripts/summarize_results.py --date YYYY-MM-DD`\n"
)

RUN_DAY_DEBUG = (
    "## Run-Day Errors & Debugging (auto)\n\n"
    "### Quick checks\n"
    "- Run `python scripts/run_day_simple.py --help` to ensure argparse is intact\n"
    "- Confirm required files are present (see Scripts Inventory banner below)\n"
    "- If data is missing for the prior trading day, check your data fetch or market calendar logic\n"
    "- Inspect logs/console output for `[ERR]` lines\n\n"
    "### Common issues\n"
    "- **No results CSV**: verify universe symbols and minute data are present\n"
    "- **Empty CSV**: strategy filters may be too strict; confirm scenario config\n"
)

def build_user_guide(scripts_index_md: str) -> str:
    parts = [
        "# USER GUIDE\n\n"
        "This guide explains how to run and validate daily backtests, where outputs are written,\n"
        "and how to debug common issues.\n\n"
        "*(This file is auto-generated by refresh_docs.py. Do not edit by hand.)*\n",
        RUN_DAY_SUCCESS,
        HYBRID_SINGLE,
        HYBRID_RANGE,
        RUN_DAY_DEBUG,
        "## Scripts Inventory (auto)\n",
        scripts_index_md,
    ]
    return "\n\n".join(parts)

def maybe_commands_appendix() -> str:
    for p in [
        REPO_ROOT / "Docs" / "Midas_Backtesting_Commands.md",
        REPO_ROOT / "Docs" / "Test Commands" / "Midas_Backtesting_Commands_v1.2.md",
        REPO_ROOT / "Docs" / "Test Commands" / "Midas_Backtesting_Commands.md",
    ]:
        if p.exists():
            return "\n\n---\n\n## Appendix: Commands Reference\n\n" + read_text(p)
    return ""

def build_dev_guide(summary_table: str, json_table: str) -> str:
    parts = [
        "# Midas_V2 Developer Guide\n\n"
        "This is a living reference for parameters, files, scenarios, directory layout, and one-line commands.\n\n"
        "## Key Folders\n"
        "- config/  (scenarios.json, settings.toml)\n"
        "- scripts/  (run_backtest.*, run_all_scenarios.*)\n"
        "- src/midas_v2/  (engine, strategy, cli)\n"
        "- Docs/  (DEV_GUIDE.md, Refresh-Docs.ps1)\n"
        "- data/samples/  (CSV with header: time,open,high,low,close,volume)\n"
        "- out/YYYYMMDD/SCENARIO/  (results_YYYY-MM-DD.csv)\n\n",
        "### Run Cheat-Sheet\n"
        "- All scenarios (PowerShell): .\\scripts\\run_all_scenarios.ps1 -Date 2025-08-05\n"
        "- One scenario (PowerShell): .\\scripts\\run_backtest.ps1 -Date 2025-08-05 -Scenario E\n"
        "- Python direct: python -m midas_v2.cli backtest --date 2025-08-05 --scenario E --universe data/samples/universe_sample.txt --out out\\20250805\\E\n\n"
        "> **Gotcha:** Compose expects the **full RAW file** for `--raw`, e.g.  `--raw data/raw/universe_topgappers_2025-08-05.txt`.\n"
        "> Using a prefix may produce `rawTop=0` (news-only).\n\n",
        HYBRID_SINGLE,
        HYBRID_RANGE,
        "### Strategy presets (summary view)\n\n",
        summary_table or "_No scenarios found in config/scenarios.json_\n\n",
        "### Strategy presets from config/scenarios.json\n\n",
        json_table or "_No scenarios found in config/scenarios.json_\n\n",
        "### Catalyst Hybrid Notes (auto)\n\n",
        "- Compose expects **full RAW path** for `--raw`, e.g. `data/raw/universe_topgappers_<DATE>.txt`.\n"
        "- Using a prefix may produce `rawTop=0` (news-only).\n",
        maybe_commands_appendix(),
    ]
    return "\n".join(parts)

# ---------------- Main --------------------------------------------------------

def main():
    if not DOCS_DIR.exists():
        err(f"[ERR] Docs folder not found at {DOCS_DIR}. Create it first.")
        sys.exit(1)

    log(f"[Docs] Using repo root: {REPO_ROOT}")

    # 1) Scripts index (always regenerated)
    scripts_index_md, missing = generate_scripts_index()

    # 2) Build fresh USER_GUIDE and DEV_GUIDE content
    summary_table, json_table = build_scenario_tables()
    user_md = build_user_guide(scripts_index_md)
    dev_md  = build_dev_guide(summary_table, json_table)

    # 3) Write files (always overwrite)
    write_text(USER_GUIDE_PATH, user_md)
    write_text(DEV_GUIDE_PATH,  dev_md)

    # 4) Final status
    if missing:
        err(f"[WARN] Missing required scripts: {', '.join(missing)}")
        sys.exit(2)
    log("[OK] Refresh complete; required scripts present.")
    sys.exit(0)

if __name__ == "__main__":
    main()
