# file: Docs/refresh_docs.py
# Purpose: Refresh docs, auto-inject:
#   1) Scripts Index + Required Scripts check (into USER_GUIDE.md & DEV_GUIDE.md)
#   2) run_day_simple.py sections: Success path + Errors/Debugging (into USER_GUIDE.md)
#   3) Optional PDF export via pandoc (if available)
#
# Usage:
#   python Docs/refresh_docs.py --root . --export pdf
#   python Docs/refresh_docs.py --root . --export none
#
# Safe behavior:
# - If USER_GUIDE.md/DEV_GUIDE.md do not exist, leaves them alone (except USER_GUIDE can be created if missing).
# - Only updates/creates sections titled with "(auto)" headings; rest of your docs remain intact.

import argparse
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import List, Tuple

# ---------------- Config ------------------------------------------------------

REQUIRED_SCRIPTS = [
    "scripts/run_day_simple.py",
    "scripts/summarize_results.py",
    "scripts/topgappers.py",
    "scripts/fetch_minutes_polygon.py",
    "scripts/run_all_scenarios.ps1",
]

SCRIPT_EXTENSIONS   = {".py", ".ps1", ".cmd", ".bat"}   # what to include in index
IGNORE_SUBSTRINGS   = {".git", "venv", "__pycache__"}   # folders to ignore

GUIDES_TO_TOUCH     = ["Docs/USER_GUIDE.md", "Docs/DEV_GUIDE.md"]  # inventory injection
USER_GUIDE_PATH     = "Docs/USER_GUIDE.md"                          # success/debug sections target
SCRIPTS_INDEX_FILE  = "Docs/SCRIPTS_INDEX.md"

INVENTORY_SECTION_TITLE = "## Scripts Inventory (auto)"

# Snippet files for run_day_simple sections (edit these anytime):
RUN_DAY_SNIPPETS = [
    # (Section Title, Snippet Path, Default Content if snippet missing)
    ("## Run-Day Success Sequence (auto)", "Docs/sections/run_day_success.md",
     """### Overview
This section documents the *successful* sequence after running:
`python scripts/run_day_simple.py --date YYYY-MM-DD --scenario B`

1. **Top gappers fetched** (Polygon or your source)  
2. **Universe file written** (e.g., `data/samples/universe_sample.txt`)  
3. **Minute data fetched** into `data/...`  
4. **Backtest runs** for chosen scenario; results to `out/<YYYYMMDD>/<Scenario>/results_YYYY-MM-DD.csv`  
5. **Summarize** via `python scripts/summarize_results.py --date YYYY-MM-DD`

> Edit `Docs/sections/run_day_success.md` to keep this aligned with your exact outputs.
"""),
    ("## Run-Day Errors & Debugging (auto)", "Docs/sections/run_day_debug.md",
     """### Quick checks
- Run `python scripts/run_day_simple.py --help` to ensure argparse is intact
- Confirm required files are present (see Scripts Inventory banner above)
- If data is missing for the prior trading day, check your data fetch or market calendar logic
- Inspect logs/console output for `[ERR]` lines

### Common issues
- **No results CSV**: verify universe symbols and minute data are present
- **Empty CSV**: strategy filters may be too strict; confirm scenario config

> Edit `Docs/sections/run_day_debug.md` to add your specific error cases and remedies.
"""),
]

# -------------- Helpers -------------------------------------------------------

def log(msg: str):
    print(msg, flush=True)

def err(msg: str):
    print(msg, file=sys.stderr, flush=True)

def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""
    except Exception as e:
        err(f"[WARN] Could not read {path}: {e}")
        return ""

def write_text(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")

def is_ignored(p: Path) -> bool:
    s = p.as_posix().lower()
    return any(tok in s for tok in IGNORE_SUBSTRINGS)

# -------------- Scripts Index + Required Check --------------------------------

def generate_scripts_index(root: Path, out_path: Path) -> Tuple[str, List[str]]:
    files: List[Path] = []
    for p in root.rglob("*"):
        if p.is_file() and p.suffix.lower() in SCRIPT_EXTENSIONS and not is_ignored(p):
            files.append(p)

    lines = [
        "# Script Index",
        "",
        "(auto-generated by refresh_docs.py; do not edit by hand)",
        "",
    ]
    for p in sorted(files, key=lambda x: x.as_posix().lower()):
        rel = p.relative_to(root).as_posix()
        try:
            with open(p, "r", errors="ignore", encoding="utf-8") as fh:
                first = (fh.readline() or "").strip()
        except Exception:
            first = ""
        mtime = time.strftime("%Y-%m-%d", time.localtime(p.stat().st_mtime))
        lines.append(f"- `{rel}` — {mtime} — {first[:160]}")

    md = "\n".join(lines)
    write_text(out_path, md)

    missing: List[str] = [r for r in REQUIRED_SCRIPTS if not (root / r).exists()]
    return md, missing

def inject_inventory_section(doc_md: str, scripts_index_md: str, missing: List[str]) -> str:
    banner = "> Required scripts: **All present**" if not missing else "> **Missing scripts:** " + ", ".join(missing)
    section = f"\n{INVENTORY_SECTION_TITLE}\n{banner}\n\n{scripts_index_md}\n"

    if INVENTORY_SECTION_TITLE in doc_md:
        # Replace existing section from title to next H2 (##) or end
        pattern = re.compile(
            rf"{re.escape(INVENTORY_SECTION_TITLE)}.*?(?=\n## |\Z)",
            flags=re.DOTALL | re.IGNORECASE,
        )
        if pattern.search(doc_md):
            doc_md = pattern.sub(lambda m: section.strip() + "\n", doc_md)
        else:
            doc_md = doc_md.rstrip() + "\n" + section
    else:
        doc_md = doc_md.rstrip() + "\n" + section

    return doc_md

# -------------- Run-Day Sections ----------------------------------------------

def load_snippet_or_default(root: Path, rel_path: str, default_text: str) -> str:
    p = root / rel_path
    if p.exists():
        return read_text(p)
    return default_text

def inject_or_replace_section(doc_md: str, title: str, body_md: str) -> str:
    """
    Replace (or append) a section that begins with 'title' up to the next H2 '## ' or end.
    """
    section = f"\n{title}\n\n{body_md.strip()}\n"
    if title in doc_md:
        pattern = re.compile(rf"{re.escape(title)}.*?(?=\n## |\Z)", flags=re.DOTALL | re.IGNORECASE)
        if pattern.search(doc_md):
            return pattern.sub(lambda m: section.strip() + "\n", doc_md)
    # Append if not found
    return doc_md.rstrip() + "\n" + section

def ensure_user_guide_exists(root: Path, path: Path):
    if not path.exists():
        skeleton = """# USER GUIDE

This guide explains how to run and validate daily backtests, where outputs are written,
and how to debug common issues.

*(This file was created automatically by refresh_docs.py. Feel free to edit.)*
"""
        write_text(path, skeleton)
        log(f"[Docs] Created {path}")

def inject_run_day_sections(root: Path, user_guide_md: str) -> str:
    updated = user_guide_md
    for (title, rel_path, default_text) in RUN_DAY_SNIPPETS:
        body = load_snippet_or_default(root, rel_path, default_text)
        updated = inject_or_replace_section(updated, title, body)
    return updated

# -------------- PDF Export ----------------------------------------------------

def export_markdown_to_pdf(md_path: Path, pdf_path: Path) -> bool:
    if shutil.which("pandoc") is None:
        log(f"[PDF] Pandoc not found in PATH. Skipping PDF for {md_path.name}.")
        return False
    try:
        subprocess.check_call(["pandoc", str(md_path), "-o", str(pdf_path)],
                              stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
        log(f"[PDF] Wrote {pdf_path}")
        return True
    except subprocess.CalledProcessError:
        err(f"[PDF] Pandoc failed for {md_path}")
        return False

# -------------- Main ----------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Refresh docs (Python). Inject inventory + run-day sections.")
    parser.add_argument("--root", default=".", help="Repo root (default: current directory).")
    parser.add_argument("--export", choices=["none", "pdf"], default="pdf",
                        help="Export guides to PDF (default: pdf).")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    docs_dir = root / "Docs"
    if not docs_dir.exists():
        err(f"[ERR] Docs folder not found at {docs_dir}. Create it or run with --root pointing to repo root.")
        sys.exit(1)

    log(f"[Docs] Using repo root: {root}")

    # 1) Scripts Index + Required Check
    scripts_index_path = root / SCRIPTS_INDEX_FILE
    scripts_index_md, missing = generate_scripts_index(root, scripts_index_path)
    log(f"[Docs] Wrote {scripts_index_path}")

    # 2) Inject inventory into USER_GUIDE.md and DEV_GUIDE.md (if present)
    touched_any = False
    for rel in GUIDES_TO_TOUCH:
        gp = root / rel
        if gp.exists():
            original = read_text(gp)
            updated  = inject_inventory_section(original, scripts_index_md, missing)
            if updated != original:
                write_text(gp, updated)
                log(f"[Docs] Injected Scripts Inventory into {gp}")
            else:
                log(f"[Docs] No inventory changes in {gp}")
            touched_any = True

    if not touched_any:
        log("[Docs] USER_GUIDE.md and DEV_GUIDE.md not found for inventory injection (index still generated).")

    # 3) Ensure USER_GUIDE exists and inject run_day sections
    ug_path = root / USER_GUIDE_PATH
    ensure_user_guide_exists(root, ug_path)
    ug_original = read_text(ug_path)
    ug_updated  = inject_run_day_sections(root, ug_original)
    if ug_updated != ug_original:
        write_text(ug_path, ug_updated)
        log(f"[Docs] Injected Run-Day sections into {ug_path}")
    else:
        log(f"[Docs] No run-day changes needed in {ug_path}")

    # 4) Optional PDF export
    if args.export == "pdf":
        for rel in {USER_GUIDE_PATH, *GUIDES_TO_TOUCH}:
            md_path = root / rel
            if md_path.exists():
                export_markdown_to_pdf(md_path, md_path.with_suffix(".pdf"))

    # 5) Exit code reflects missing required scripts (useful in CI)
    if missing:
        err(f"[WARN] Missing required scripts: {', '.join(missing)}")
        sys.exit(2)
    log("[OK] Refresh complete; required scripts present.")
    sys.exit(0)

if __name__ == "__main__":
    main()